### PR TITLE
Refactor the transform method

### PR DESCRIPTION
**Pull request by krmahadevan**
Refactoring the transform() method for the following 
benefits:
* Modularised code
* Enhanced readability
* Reduction in code complexity
* Code becomes testable

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @baubakg

**Comment by baubakg** [comment]
Wow this is some change. Please let me first learn from it as you are using factories which I never use :)

**Comment by baubakg** [comment]
seems also that my github actions are not adapted to forks yet

**Comment by krmahadevan** [comment]
@baubakg - I think I have fixed the github actions as well so that it supports building on PRs. Please check

**Comment by baubakg** [comment]
At leeast the unit tests work now. I have to see about the pgp issues related to your fork.

**Comment by krmahadevan** [comment]
@baubakg - Let me know when this PR can be merged, because I have a fix for https://github.com/adobe/phased-testing/issues/49 ready as the next one.

**Comment by baubakg** [comment]
awesome. I think what is missing to merge for this is thee coverage issue

**Comment by krmahadevan** [comment]
>  I think what is missing to merge for this is the coverage issue, which has gone a bit down.

Can we consider tackling it separately because now it should be able to add more tests since the code is decoupled and is also testable. I am not sure how much time I would have at my hand and thought I should wrap up this PR and the next one in whatever time I have.

Let me know if we can make an exception here

**Comment by baubakg** [comment]
Your my first contributer. Yes

**Pull request merged**
