### PR TITLE
Code clean-up

### PR DESCRIPTION
**Pull request by krmahadevan**
* Use wild card as types instead of raw param type for Class
* Use String instead of StringBuilder when trying to build a 
String wherein there is no iterations
* Favour streams over iterators
* don’t use “newInstance()”

### CODE REVIEW

**Comment by krmahadevan** [comment]
@baubakg - This PR does bring down the code coverage %age by a marginal value, but I think it basically addresses a lot of things in terms of betterment in code. I will leave it to you to decide if you are fine with going ahead with the merge (if there are no observations that is), because I am not sure if its going to be a fruitful exercise to try and add tests to keep the tool happy :)

**Comment by baubakg** [comment]
@krmahadevan this seems to have introduced a compilation error after the merge

**Comment by baubakg** [comment]
https://github.com/adobe/phased-testing/runs/5141735165?check_suite_focus=true

```
Warning:  
Warning:  Some problems were encountered while building the effective model for com.adobe.campaign.tests.phased:phased-testing-testng:jar:7.0.10-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.apache.maven:maven-model-builder:3.8.4:super-pom, jar:file:/usr/share/apache-maven-3.8.4/lib/maven-model-builder-3.8.4.jar!/org/apache/maven/model/pom-4.0.0.xml, line 137, column 19
Warning:  
Warning:  It is highly recommended to fix these problems because they threaten the stability of your build.
Warning:  
Warning:  For this reason, future Maven versions might no longer support building such malformed projects.
Warning:  
[INFO] 
[INFO] -------< com.adobe.campaign.tests.phased:phased-testing-testng >--------
[INFO] Building com.adobe.campaign.tests.phased:phased-testing-testng 7.0.10-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ phased-testing-testng ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:prepare-agent (default) @ phased-testing-testng ---
Warning:  The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] argLine set to -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/home/runner/work/phased-testing/phased-testing/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ phased-testing-testng ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.9.0:compile (default-compile) @ phased-testing-testng ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 23 source files to /home/runner/work/phased-testing/phased-testing/target/classes
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/phased-testing/phased-testing/src/main/java/com/adobe/campaign/tests/integro/phased/PhasedTestManager.java:[1190,25] unreported exception java.lang.Throwable; must be caught or declared to be thrown
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.490 s
[INFO] Finished at: 2022-02-10T13:49:16Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.9.0:compile (default-compile) on project phased-testing-testng: Compilation failure
Error:  /home/runner/work/phased-testing/phased-testing/src/main/java/com/adobe/campaign/tests/integro/phased/PhasedTestManager.java:[1190,25] unreported exception java.lang.Throwable; must be caught or declared to be thrown
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.
```

**Comment by krmahadevan** [comment]
@baubakg - I have created a new PR after rebasing off of main. Please check.

**Pull request merged**
